#!/usr/bin/env ruby
#^syntax detection

site 'https://supermarket.getchef.com/api/v1'

cookbook 'apt', '2.6.1'
cookbook 'java', '1.50.0'
cookbook 'redisio', '2.6.1'
cookbook 'postgresql', '6.1.1'
cookbook 'database', '6.1.1'
cookbook 'solr', '0.6.0'
